
# ____              _     _    ____
#/ ___|  __ _ _   _(_) __| |  / ___| __ _ _ __ ___   ___
#\___ \ / _` | | | | |/ _` | | |  _ / _` | '_ ` _ \ / _ \
# ___) | (_| | |_| | | (_| | | |_| | (_| | | | | | |  __/
#|____/ \__, |\__,_|_|\__,_|  \____|\__,_|_| |_| |_|\___|
#          |_|

# - By parsa3323
# - Docs :